# Compiler
CC=clang
 
# Flags for compiler
CC_FLAGS=-W         \
         -Wall      \
         -pedantic


linkedlist : LinkedList/LinkedList.c
	$(CC) -o LinkedList/linkedlist LinkedList/LinkedList.c $(CC_FLAGS)
